import type { FoundationUnit } from './foundations.ts';
import type { Register, Unit, VocabularyItem } from './curriculum.ts';

type PhraseSeed = readonly [
  id: string,
  fil: string,
  en: string,
  note?: string,
  register?: Register,
];

type WordSeed = readonly [id: string, fil: string, en: string, note?: string];

type DialogueSeed = readonly [
  situation: string,
  line: string,
  lineEn: string,
  reply: string,
  replyEn: string,
  alternativeOne: string,
  alternativeTwo: string,
  note: string,
];

type UnitSeed = {
  id: string;
  title: string;
  titleFil: string;
  description: string;
  canDo: string;
  soundTitle: string;
  soundModel: string;
  soundFocus: string;
  syllables: string;
  pattern: Unit['pattern'];
  phrases: PhraseSeed[];
  words: WordSeed[];
  dialogue: DialogueSeed;
};

function makeUnit(seed: UnitSeed): Unit {
  const [
    situation,
    line,
    ,
    reply,
    ,
    alternativeOne,
    alternativeTwo,
    dialogueNote,
  ] = seed.dialogue;
  return {
    id: seed.id,
    number: 0,
    title: seed.title,
    titleFil: seed.titleFil,
    description: seed.description,
    canDo: seed.canDo,
    minutes: 37,
    soundFocus: seed.soundFocus,
    pattern: seed.pattern,
    phrases: seed.phrases.map(([id, fil, en, note, register]) => ({
      id,
      fil,
      en,
      register: register ?? 'neutral',
      note:
        note ??
        `Learn this as a complete model, then replace one meaningful part when the context changes.`,
    })),
    dialogue: {
      situation,
      line,
      reply,
      alternatives: [alternativeOne, alternativeTwo],
      note: dialogueNote,
    },
  };
}

function makeFoundation(seed: UnitSeed): FoundationUnit {
  const [situation, line, lineEn, reply, replyEn] = seed.dialogue;
  const drillTransform = seed.pattern.transform.split('·')[0].trim();
  const transformation = drillTransform.split('→').map((part) => part.trim());
  const transformationPrompt = transformation[0] ?? seed.pattern.transform;
  const transformationAnswer = transformation.at(-1) ?? seed.phrases[0][1];
  const grammarOptions = [
    transformationAnswer,
    ...seed.phrases.map((phrase) => phrase[1]),
  ]
    .filter((option, index, options) => options.indexOf(option) === index)
    .slice(0, 3);
  const readingOptions = [reply, ...seed.phrases.map((phrase) => phrase[1])]
    .filter((option, index, options) => options.indexOf(option) === index)
    .slice(0, 3);
  return {
    pronunciation: {
      title: seed.soundTitle,
      explanation: seed.soundFocus,
      model: seed.soundModel,
      syllables: seed.syllables,
      coach:
        'Play the model, repeat it slowly without reducing the vowels, then say the whole line once at a natural pace.',
      drill: {
        question: `Which practice guide keeps the model's syllables clear?`,
        options: [
          seed.syllables,
          'Reduce unstressed vowels to an English “uh.”',
          'Skip the final syllable to speak faster.',
        ],
        correct: seed.syllables,
        note: 'Clear vowels, audible syllables, and well-placed stress matter more than copying an American English rhythm.',
      },
    },
    grammar: {
      title: `Core pattern: ${seed.pattern.frame}`,
      explanation: seed.pattern.note,
      formula: seed.pattern.frame,
      examples: seed.phrases.slice(0, 2).map(([, fil, en]) => ({ fil, en })),
      drill: {
        question: `Apply the unit pattern: transform “${transformationPrompt}.”`,
        options: grammarOptions,
        correct: transformationAnswer,
        note: seed.pattern.note,
      },
    },
    reading: {
      title: situation,
      passage: `A: ${line} B: ${reply}`,
      translation: `A: ${lineEn} B: ${replyEn}`,
      drill: {
        question: 'Which reply completes the exchange?',
        options: readingOptions,
        correct: reply,
        note: seed.dialogue[7],
      },
    },
  };
}

const seeds: UnitSeed[] = [
  {
    id: 'nominal-sentences',
    title: 'People & descriptions',
    titleFil: 'Guro si Ben.',
    description:
      'Build sentences without an English-style “is,” and mark names and common nouns clearly.',
    canDo: 'I can identify and describe people, places, and things.',
    soundTitle: 'Crisp final vowels and a light Filipino r',
    soundModel: 'Guro si Ben. Mabait ang guro.',
    soundFocus:
      'Keep the final vowels audible in guro and bata. Make the r in guro a quick tongue tap rather than a long American r.',
    syllables: 'GU-ro si Ben · ma-ba-IT ang GU-ro',
    pattern: {
      frame: '[description or identity] + ang/si + [subject]',
      transform: 'Guro si Ben. → Mabait si Ben.',
      note: 'Tagalog commonly places the predicate first. Use “si” before one personal name and “ang” before the focused common-noun phrase; neither marker is simply the English word “the.”',
    },
    phrases: [
      [
        'siya-si-rosa',
        'Siya si Rosa.',
        'She is Rosa.',
        'Use “si” before the personal name Rosa.',
      ],
      [
        'guro-si-ben',
        'Guro si Ben.',
        'Ben is a teacher.',
        'No separate word for “is” is required in this identifying sentence.',
      ],
      ['mabait-guro', 'Mabait ang guro.', 'The teacher is kind.'],
      ['doktor-kapatid', 'Doktor ang kapatid ko.', 'My sibling is a doctor.'],
      [
        'sina-kapitbahay',
        'Mga kapitbahay ko sina Liza at Jun.',
        'Liza and Jun are my neighbors.',
        'Use “sina” before two or more personal names.',
      ],
      ['masaya-bata', 'Masaya ang mga bata.', 'The children are happy.'],
      [
        'bahay-ay-tahimik',
        'Ang bahay ay tahimik.',
        'The house is quiet.',
        'The “ay” order is useful in careful or formal speech; predicate-first order is usually more conversational.',
        'formal',
      ],
    ],
    words: [
      ['guro', 'guro', 'teacher'],
      ['doktor', 'doktor', 'doctor'],
      ['kapatid', 'kapatid', 'sibling'],
      ['kapitbahay', 'kapitbahay', 'neighbor'],
      ['bata', 'bata', 'child'],
      ['bahay', 'bahay', 'house'],
      ['mabait', 'mabait', 'kind'],
      ['masaya', 'masaya', 'happy'],
    ],
    dialogue: [
      'Meeting a new colleague',
      'Sino si Ben?',
      'Who is Ben?',
      'Guro si Ben.',
      'Ben is a teacher.',
      'Dalawang tiket po.',
      'Nasa kusina ang pagkain.',
      'The reply identifies Ben by placing the role first.',
    ],
  },
  {
    id: 'pronouns-demonstratives',
    title: 'Pronouns & pointing',
    titleFil: 'Ito, iyan, iyon',
    description:
      'Keep track of who is speaking and point to things by distance from speaker and listener.',
    canDo: 'I can use personal pronouns and the three-way pointing system.',
    soundTitle: 'Do not swallow the vowels in pronouns',
    soundModel: 'Ako. Ikaw. Kayo. Ito. Iyan. Iyon.',
    soundFocus:
      'Keep ako, ikaw, kayo, and iyon fully syllabic. In careful speech, iyon has two clear syllables: i-yon.',
    syllables: 'a-KO · i-KAW · ka-YO · i-TO · i-YAN · i-YON',
    pattern: {
      frame: 'ito (near me) · iyan (near you) · iyon (away from both)',
      transform: 'Ito ang susi. → Iyan ang susi.',
      note: 'Tagalog distinguishes things near the speaker, near the listener, and away from both. “Tayo” includes the listener; “kami” excludes the listener.',
    },
    phrases: [
      [
        'ito-susi',
        'Ito ang susi.',
        'This is the key.',
        '“Ito” points near the speaker.',
      ],
      [
        'iyan-bag',
        'Iyan ba ang bag mo?',
        'Is that your bag?',
        '“Iyan” points near the listener.',
      ],
      [
        'siya-kapatid',
        'Siya ang kapatid ko.',
        'He/She is my sibling.',
        '“Siya” does not mark gender.',
      ],
      [
        'kami-chicago',
        'Taga-Chicago kami.',
        'We are from Chicago. (not including you)',
        '“Kami” excludes the listener.',
      ],
      [
        'tayo-mauuna',
        'Mauuna tayo.',
        'We will go first. (including you)',
        '“Tayo” includes the listener.',
      ],
      [
        'kayo-guro',
        'Kayo po ba ang guro?',
        'Are you the teacher?',
        '“Kayo” is the usual respectful singular “you” and also plural “you.”',
        'polite',
      ],
      [
        'iyon-istasyon',
        'Iyon ang istasyon.',
        'That is the station over there.',
        '“Iyon” points away from both speaker and listener.',
      ],
    ],
    words: [
      ['siya', 'siya', 'he / she'],
      ['kami', 'kami', 'we (not you)'],
      ['tayo', 'tayo', 'we (including you)'],
      ['kayo', 'kayo', 'you (plural or respectful)'],
      ['sila', 'sila', 'they / them'],
      ['ito', 'ito', 'this, near me'],
      ['iyan', 'iyan', 'that, near you'],
      ['iyon', 'iyon', 'that, away from both'],
    ],
    dialogue: [
      'Identifying a teacher',
      'Kayo po ba ang guro?',
      'Are you the teacher?',
      'Opo, ako ang guro.',
      'Yes, I am the teacher.',
      'Kape o tsaa?',
      'Walang tubig.',
      '“Opo” answers respectfully, and “ako” identifies the speaker.',
    ],
  },
  {
    id: 'linkers-descriptions',
    title: 'Linking descriptions',
    titleFil: 'Mabait na tao',
    description:
      'Join descriptions to nouns with -ng, -g, or na and keep natural word order.',
    canDo: 'I can describe people and things with linked phrases.',
    soundTitle: 'Let attached -ng flow into the next word',
    soundModel: 'Magandang araw. Malaking bahay.',
    soundFocus:
      'In magandang and malaking, the final -ng is one sound like the end of “sing.” Do not release a separate hard g.',
    syllables: 'ma-gan-DANG A-raw · ma-la-KING BA-hay',
    pattern: {
      frame: '[vowel] + -ng · [final n] + -g · [other consonant] + na',
      transform: 'maganda + araw → magandang araw',
      note: 'The linker joins words that belong together. Attach -ng after a vowel, use -g after final n, and use separate “na” after most other consonants.',
    },
    phrases: [
      ['magandang-araw', 'Magandang araw.', 'Good day.'],
      ['mabait-na-tao', 'Mabait na tao siya.', 'He/She is a kind person.'],
      ['malaking-bahay', 'Malaking bahay iyon.', 'That is a big house.'],
      ['mabilis-na-tren', 'Mabilis na tren ito.', 'This is a fast train.'],
      [
        'bagong-kaibigan',
        'Bago kong kaibigan si Maya.',
        'Maya is my new friend.',
        '“Ko” follows bago; the linker then attaches to ko: bago + ko + -ng + kaibigan → bago kong kaibigan.',
      ],
      ['mainit-na-kape', 'Mainit na kape ito.', 'This is hot coffee.'],
      [
        'masarap-na-pagkain',
        'Masarap na pagkain iyan.',
        'That is delicious food.',
      ],
    ],
    words: [
      ['maganda', 'maganda', 'beautiful / good'],
      ['mabait', 'mabait', 'kind'],
      ['malaki', 'malaki', 'big'],
      ['mabilis', 'mabilis', 'fast'],
      ['bago', 'bago', 'new'],
      ['mainit', 'mainit', 'hot'],
      ['masarap', 'masarap', 'delicious'],
      ['tao', 'tao', 'person'],
    ],
    dialogue: [
      'Describing a new neighbor',
      'Kumusta ang bago mong kapitbahay?',
      'How is your new neighbor?',
      'Mabait na tao siya.',
      'He/She is a kind person.',
      'Alas-diyes na.',
      'Kailangan ko ng doktor.',
      'The linked phrase “mabait na tao” keeps the description with the noun.',
    ],
  },
  {
    id: 'possession',
    title: 'Ownership & relationships',
    titleFil: 'Kanino ito?',
    description:
      'Say who owns something with possessive pronouns and personal-name markers.',
    canDo: 'I can ask and answer who something belongs to.',
    soundTitle: 'Keep ni, niya, and ninyo distinct',
    soundModel: 'Ni. Niya. Ninyo. Kanino?',
    soundFocus:
      'Practice ni, niya, and ninyo slowly. The y in niya and ninyo glides directly into the following vowel.',
    syllables: 'ni · ni-YA · nin-YO · ka-NI-no',
    pattern: {
      frame:
        'akin/iyo/kaniya/amin/atin/inyo/kanila + ang/ito/iyan/iyon · [owned thing] + ko/mo/niya/namin/natin/ninyo/nila',
      transform: 'bag ko → bag niya',
      note: 'Use independent forms such as akin/iyo/kaniya when possession is the predicate; clitic forms such as ko/mo/niya follow the thing owned. Use ni/nina before personal names.',
    },
    phrases: [
      ['akin-ito', 'Akin ito.', 'This is mine.'],
      ['iyo-iyan', 'Iyo ba iyan?', 'Is that yours?'],
      ['kaniya-bag', 'Kaniya ang bag.', 'The bag is his/hers.'],
      [
        'plano-natin',
        'Plano natin ito.',
        'This is our plan. (including you)',
        '“Natin” includes the listener; “namin” does not.',
      ],
      [
        'telepono-ninyo',
        'Nasaan ang telepono ninyo?',
        'Where is your phone?',
        '“Ninyo” is respectful singular or plural.',
      ],
      [
        'bag-ni-ana',
        'Bag ni Ana ito.',
        'This is Ana’s bag.',
        'Use “ni” before one person’s name in this possessive phrase.',
      ],
      ['kanino-susi', 'Kanino ang susi?', 'Who does the key belong to?'],
    ],
    words: [
      ['akin', 'akin', 'mine'],
      ['iyo', 'iyo', 'yours'],
      ['kaniya', 'kaniya', 'his / hers'],
      ['amin', 'amin', 'ours, not yours'],
      ['atin', 'atin', 'ours, including yours'],
      ['kanino', 'kanino', 'whose'],
      ['bag', 'bag', 'bag'],
      ['susi', 'susi', 'key'],
    ],
    dialogue: [
      'Finding a misplaced key',
      'Kanino ang susi?',
      'Who does the key belong to?',
      'Akin iyan, salamat.',
      'That is mine, thank you.',
      'Masarap ang pagkain.',
      'Kita tayo bukas.',
      '“Akin” stands as the ownership answer; “iyan” points to the key near the listener.',
    ],
  },
  {
    id: 'questions-particles',
    title: 'Questions & small particles',
    titleFil: 'Ano? Sino? Bakit?',
    description:
      'Ask useful open and yes/no questions, then hear how small particles shape meaning.',
    canDo: 'I can ask what, who, which, why, how, and yes/no questions.',
    soundTitle: 'Keep question words fully syllabic',
    soundModel: 'Ano? Sino? Alin? Bakit? Paano?',
    soundFocus:
      'Say paano as pa-A-no, preserving both adjacent a vowels. Keep the final o audible in ano and sino.',
    syllables: 'a-NO · SI-no · a-LIN · ba-KIT · pa-A-no',
    pattern: {
      frame:
        '[question word] + (short clitics) + rest · [first predicate/topic] + (short clitics) + ba + rest',
      transform: 'Handa ka na. → Handa ka na ba?',
      note: 'Question words replace the missing information. The particle “ba” makes a neutral yes/no question; “na” can mean already/now, while “pa” can mean still/yet.',
    },
    phrases: [
      ['ano-ito', 'Ano ito?', 'What is this?'],
      ['sino-siya', 'Sino siya?', 'Who is he/she?'],
      ['alin-gusto', 'Alin ang gusto mo?', 'Which one do you want?'],
      ['bakit-nandito', 'Bakit ka nandito?', 'Why are you here?'],
      ['paano-gamitin', 'Paano ito gamitin?', 'How do you use this?'],
      [
        'hindi-pa',
        'Hindi pa.',
        'Not yet.',
        '“Pa” keeps the situation open: it has not happened yet.',
      ],
      ['handa-na-ba', 'Handa ka na ba?', 'Are you ready now?'],
    ],
    words: [
      ['ano', 'ano', 'what'],
      ['sino', 'sino', 'who'],
      ['alin', 'alin', 'which'],
      ['bakit', 'bakit', 'why'],
      ['paano', 'paano', 'how'],
      ['ba', 'ba', 'yes/no question particle'],
      ['na', 'na', 'already / now'],
      ['pa', 'pa', 'still / yet'],
    ],
    dialogue: [
      'Checking whether a friend is ready',
      'Handa ka na ba?',
      'Are you ready now?',
      'Hindi pa. Sandali lang.',
      'Not yet. Just a moment.',
      'Kaniya ang bag.',
      'Diretso lang.',
      '“Hindi pa” means not yet; “sandali lang” asks for a short wait.',
    ],
  },
  {
    id: 'existence-quantity',
    title: 'Existence & quantity',
    titleFil: 'Mayroon o wala?',
    description:
      'Say what exists, what someone has, and how much or how many there are.',
    canDo: 'I can describe availability, absence, and simple quantities.',
    soundTitle: 'Hear mayroon and conversational meron',
    soundModel: 'Mayroon. Meron. Wala.',
    soundFocus:
      'Careful “mayroon” has three syllables. Conversational “meron” is common; recognize both without treating one as incorrect.',
    syllables: 'may-ro-ON · ME-ron · wa-LA',
    pattern: {
      frame:
        'may + noun · mayroon/meron + linked pronoun · walang + noun · wala + ang + focused/known noun',
      transform: 'May tubig. → Walang tubig.',
      note: 'Use “may” directly before a noun. “Mayroon” can stand alone or link to a following pronoun. Use “wala” for absence and “hindi” to negate a description or action.',
    },
    phrases: [
      ['may-pagkain', 'May pagkain sa mesa.', 'There is food on the table.'],
      [
        'mayroon-oras',
        'Mayroon akong oras.',
        'I have time.',
        '“Ako” links to mayroon as “akong.”',
      ],
      [
        'meron-sukli',
        'Meron po ba kayong sukli?',
        'Do you have change?',
        '“Meron” is a common conversational form of “mayroon.”',
        'casual',
      ],
      ['walang-tubig', 'Walang tubig.', 'There is no water.'],
      [
        'hindi-mainit',
        'Hindi mainit ang kape.',
        'The coffee is not hot.',
        'Use “hindi,” not “wala,” to negate the description “mainit.”',
      ],
      ['ilan-kailangan', 'Ilan ang kailangan mo?', 'How many do you need?'],
      ['maraming-tao', 'Maraming tao rito.', 'There are many people here.'],
    ],
    words: [
      ['may', 'may', 'there is / has + noun'],
      ['mayroon', 'mayroon', 'exists / has (standalone)'],
      ['wala', 'wala', 'none / absent'],
      ['ilan', 'ilan', 'how many'],
      ['marami', 'marami', 'many'],
      ['kaunti', 'kaunti', 'few / a little'],
      ['oras', 'oras', 'time'],
      ['sukli', 'sukli', 'change (money)'],
    ],
    dialogue: [
      'Asking for change at a shop',
      'Meron po ba kayong sukli?',
      'Do you have change?',
      'Opo, mayroon.',
      'Yes, I do.',
      'Hindi pa.',
      'Masaya ang mga bata.',
      '“Mayroon” can stand alone when the thing is already understood.',
    ],
  },
  {
    id: 'numbers-time',
    title: 'Numbers & quantities',
    titleFil: 'Dalawang tiket po.',
    description:
      'Count useful quantities, ask how many, and understand simple prices.',
    canDo: 'I can count and buy a small number of everyday items.',
    soundTitle: 'Link number words without rushing',
    soundModel: 'Dalawang tiket. Sampung piso.',
    soundFocus:
      'Keep the linker in dalawang and sampung audible. Say each vowel clearly before increasing speed.',
    syllables: 'da-la-WANG TI-ket · sam-PUNG PI-so',
    pattern: {
      frame: '[number] + -ng/na + noun · magkano/ilan + item',
      transform: 'dalawa + tiket → dalawang tiket',
      note: 'A number links to the noun it counts: use -ng after a vowel and na after most consonants. Ilan asks how many; magkano asks the price.',
    },
    phrases: [
      ['isa-dalawa-tatlo', 'Isa, dalawa, tatlo.', 'One, two, three.'],
      [
        'dalawang-tiket',
        'Dalawang tiket po.',
        'Two tickets, please.',
        '“Dalawa” takes the linker -ng before tiket.',
      ],
      ['magkano-tatlo', 'Magkano ang tatlo?', 'How much for all three?'],
      ['alas-diyes', 'Sampung piso ito.', 'This costs ten pesos.'],
      [
        'anong-oras',
        'Ilang tiket ang kailangan?',
        'How many tickets are needed?',
      ],
      [
        'lunes-klase',
        'Isang kape at dalawang tubig po.',
        'One coffee and two waters, please.',
      ],
      [
        'ikasampu-setyembre',
        'Tatlong piso ang sukli.',
        'The change is three pesos.',
        'Tatlo takes the linker -ng before piso.',
      ],
    ],
    words: [
      ['isa', 'isa', 'one'],
      ['dalawa', 'dalawa', 'two'],
      ['tatlo', 'tatlo', 'three'],
      ['sampu', 'sampu', 'ten'],
      ['ilan', 'ilan', 'how many'],
      ['magkano', 'magkano', 'how much'],
      ['piso', 'piso', 'peso'],
      ['tiket', 'tiket', 'ticket'],
    ],
    dialogue: [
      'Buying tickets',
      'Ilang tiket ang kailangan ninyo?',
      'How many tickets do you need?',
      'Dalawang tiket po.',
      'Two tickets, please.',
      'Sampung piso ito.',
      'Magkano ang tatlo?',
      'Dalawa takes the linker -ng before tiket.',
    ],
  },
  {
    id: 'comparisons',
    title: 'Comparing things',
    titleFil: 'Mas mura ito.',
    description:
      'Compare qualities, amounts, equality, and extremes in practical situations.',
    canDo: 'I can compare two choices and say which is best, more, or less.',
    soundTitle: 'Keep mas and pinaka- crisp',
    soundModel: 'Mas mura. Pinakamabilis.',
    soundFocus:
      'Do not merge mas into the next word. In pinakamabilis, keep each syllable audible before increasing speed.',
    syllables: 'mas MU-ra · pi-na-ka-ma-bi-LIS',
    pattern: {
      frame: 'mas + quality + kaysa · pinaka- + quality',
      transform: 'mura → pinakamura',
      note: 'Use “mas … kaysa” for more … than, “kasing-/magkasing-” for equality, and “pinaka-” for the highest degree within a group.',
    },
    phrases: [
      [
        'magkasinghaba',
        'Magkasinghaba ang dalawa.',
        'The two are the same length.',
      ],
      [
        'mas-mura',
        'Mas mura ito kaysa roon.',
        'This is cheaper than that one over there.',
      ],
      [
        'mas-mahal',
        'Mas mahal iyon kaysa rito.',
        'That is more expensive than this one.',
      ],
      ['napakaganda', 'Napakaganda ng bahay.', 'The house is very beautiful.'],
      ['pinakamabilis', 'Ito ang pinakamabilis.', 'This is the fastest.'],
      [
        'kasing-init',
        'Kasing-init ng kape ang tubig.',
        'The water is as hot as the coffee.',
      ],
      [
        'hindi-gaano',
        'Hindi gaanong maingay rito.',
        'It is not very noisy here.',
      ],
    ],
    words: [
      ['mas', 'mas', 'more'],
      ['kaysa', 'kaysa', 'than'],
      ['pinaka', 'pinaka-', 'most / -est'],
      ['mura', 'mura', 'cheap'],
      ['mahal', 'mahal', 'expensive'],
      ['haba', 'haba', 'length'],
      ['maingay', 'maingay', 'noisy'],
      ['gaano', 'gaano', 'how / to what degree'],
    ],
    dialogue: [
      'Choosing between two bags',
      'Alin ang gusto mo?',
      'Which one do you want?',
      'Ito. Mas mura ito kaysa roon.',
      'This one. It is cheaper than that one over there.',
      'Hindi pa.',
      'Guro si Ben.',
      'The comparison uses “mas mura … kaysa” to give a reason for the choice.',
    ],
  },
  {
    id: 'actor-focus',
    title: 'Actions & aspect',
    titleFil: 'Kumain, kumakain, kakain',
    description:
      'Track completed, ongoing, and contemplated actions while keeping the actor in focus.',
    canDo: 'I can describe who did, is doing, or will do an action.',
    soundTitle: 'Hear infixes inside -um- verbs',
    soundModel: 'Kumain. Kumakain. Kakain.',
    soundFocus:
      'In kumain, the -um- sound appears inside the root kain. Practice the completed, ongoing, and contemplated forms as rhythmic families.',
    syllables: 'ku-MA-in · ku-ma-KA-in · ka-KA-in',
    pattern: {
      frame: '-um- / mag- verb + focused actor + ng object',
      transform: 'kumain → kakain',
      note: 'These forms primarily express aspect: completed, ongoing, or contemplated action. They are not exact copies of English past, present, and future tense.',
    },
    phrases: [
      ['kumain-almusal', 'Kumain ako ng almusal.', 'I ate breakfast.'],
      ['kumakain-ngayon', 'Kumakain siya ngayon.', 'He/She is eating now.'],
      ['kakain-mamaya', 'Kakain tayo mamaya.', 'We will eat later.'],
      ['naglakad-pauwi', 'Naglakad kami pauwi.', 'We walked home.'],
      [
        'naglalakad-araw-araw',
        'Naglalakad sila araw-araw.',
        'They walk every day.',
      ],
      ['maglalakad-bukas', 'Maglalakad kayo bukas.', 'You will walk tomorrow.'],
      [
        'sino-nagluto',
        'Sino ang nagluto?',
        'Who cooked?',
        'The question asks for the actor, so the actor is the focus.',
      ],
    ],
    words: [
      ['kain', 'kain', 'eat (root)'],
      ['lakad', 'lakad', 'walk (root)'],
      ['luto', 'luto', 'cook (root)'],
      ['almusal', 'almusal', 'breakfast'],
      ['ngayon', 'ngayon', 'now'],
      ['mamaya', 'mamaya', 'later'],
      ['pauwi', 'pauwi', 'headed home'],
      ['araw-araw', 'araw-araw', 'every day'],
    ],
    dialogue: [
      'Asking about breakfast',
      'Kumain ka na ba?',
      'Have you eaten?',
      'Oo, kumain na ako.',
      'Yes, I have eaten.',
      'Dalawang tiket po.',
      'Mas mura ito.',
      'The completed actor-focused form is “kumain”; “na” adds “already/by now” and does not create completed aspect.',
    ],
  },
  {
    id: 'object-focus',
    title: 'Patient-focused actions',
    titleFil: 'Kinain ko ang mangga.',
    description:
      'Shift attention to the affected thing and contrast actor- and patient-focused sentences.',
    canDo:
      'I can choose a natural focus when the object is the main information.',
    soundTitle: 'Hear -in- and repeated aspect syllables',
    soundModel: 'Kinain. Kinakain. Kakainin.',
    soundFocus:
      'In kinain and binili, -in- appears inside the root. Keep kinakain and binibili even and syllabic rather than swallowing the repeated middle.',
    syllables: 'ki-NA-in · ki-na-KA-in · ka-ka-I-nin',
    pattern: {
      frame: '-in/-hin verb + ng/ko actor + ang focused patient',
      transform: 'Kumain ako ng mangga. → Kinain ko ang mangga.',
      note: 'Patient focus highlights the affected thing with “ang”; the actor appears in an ng-form such as “ko” or “ni Mara.” This system is richer than English active versus passive voice.',
    },
    phrases: [
      [
        'kinain-mangga',
        'Kinain ko ang mangga.',
        'I ate the mango. (mango in focus)',
      ],
      [
        'kinakain-kanin',
        'Kinakain niya ang kanin.',
        'He/She is eating the rice.',
      ],
      ['kakainin-isda', 'Kakainin natin ang isda.', 'We will eat the fish.'],
      ['binili-tiket', 'Binili ni Mara ang tiket.', 'Mara bought the ticket.'],
      [
        'binibili-gulay',
        'Binibili ko ang gulay.',
        'I am buying the vegetables.',
      ],
      ['bibilhin-ito', 'Bibilhin mo ba ito?', 'Will you buy this?'],
      [
        'ano-niluto',
        'Ano ang niluto mo?',
        'What did you cook?',
        'The unknown patient is the focus of the question.',
      ],
    ],
    words: [
      ['mangga', 'mangga', 'mango'],
      ['kanin', 'kanin', 'cooked rice'],
      ['isda', 'isda', 'fish'],
      ['tiket', 'tiket', 'ticket'],
      ['gulay', 'gulay', 'vegetable'],
      ['bili', 'bili', 'buy (root)'],
      ['kain', 'kain', 'eat (root)'],
      ['luto', 'luto', 'cook (root)'],
    ],
    dialogue: [
      'Asking what someone cooked',
      'Ano ang niluto mo?',
      'What did you cook?',
      'Niluto ko ang isda.',
      'I cooked the fish.',
      'Hindi gaanong maingay rito.',
      'Magandang araw.',
      'The patient-focused reply keeps the fish as the highlighted item.',
    ],
  },
  {
    id: 'modality-ability',
    title: 'Want, need & ability',
    titleFil: 'Gusto kong matuto.',
    description:
      'Express desires, obligation, permission, learned skills, and ability in context.',
    canDo: 'I can say what I want, need, may, can, and know how to do.',
    soundTitle: 'Link pronouns before action words',
    soundModel: 'Gusto kong matuto. Kailangan nating maghanda.',
    soundFocus:
      'Hear the linker in gusto kong and kailangan nating. Let kong or nating connect smoothly to the following action.',
    syllables: 'GUS-to kong ma-TU-to · ka-i-LA-ngan NA-ting mag-han-DA',
    pattern: {
      frame: 'modal + linked pronoun + action',
      transform: 'Gusto ko + matuto → Gusto kong matuto.',
      note: 'Many modal expressions link directly to a pronoun before another action. “Marunong” means knowing how to do something; use “matalino” for intelligent.',
    },
    phrases: [
      [
        'gusto-matuto',
        'Gusto kong matuto ng Tagalog.',
        'I want to learn Tagalog.',
      ],
      ['ayokong-umalis', 'Ayokong umalis.', 'I do not want to leave.'],
      [
        'kailangan-mag-handa',
        'Kailangan nating maghanda.',
        'We need to prepare. (including you)',
      ],
      [
        'maaari-pumasok',
        'Maaari po ba akong pumasok?',
        'May I come in?',
        '“Maaari” sounds careful or formal.',
        'formal',
      ],
      ['puwede-umupo', 'Puwede kang umupo rito.', 'You can sit here.'],
      [
        'marunong-lumangoy',
        'Marunong siyang lumangoy.',
        'He/She knows how to swim.',
      ],
      ['hindi-makatulog', 'Hindi ako makatulog.', 'I cannot sleep.'],
    ],
    words: [
      ['gusto', 'gusto', 'want / like'],
      ['ayaw', 'ayaw', 'do not want'],
      ['kailangan', 'kailangan', 'need / must'],
      ['maaari', 'maaari', 'may / possible'],
      ['puwede', 'puwede', 'can / allowed'],
      ['marunong', 'marunong', 'knows how'],
      ['matuto', 'matuto', 'to learn'],
      ['lumangoy', 'lumangoy', 'to swim'],
    ],
    dialogue: [
      'Entering a classroom',
      'Maaari po ba akong pumasok?',
      'May I come in?',
      'Oo, puwede kang pumasok.',
      'Yes, you may come in.',
      'Walang tubig.',
      'Masarap na pagkain iyan.',
      'The exchange pairs a careful permission request with a natural affirmative answer.',
    ],
  },
  {
    id: 'states-change',
    title: 'States & change',
    titleFil: 'Naging tahimik.',
    description:
      'Describe becoming, having, and entering a new state across time.',
    canDo: 'I can describe what someone becomes or comes to have.',
    soundTitle: 'Keep maging and magkaroon in clear chunks',
    soundModel: 'Maging. Nagkaroon. Magkakaroon.',
    soundFocus:
      'Practice maging and magkaroon by syllable before adding pronouns. Keep the middle vowels audible at conversational speed.',
    syllables: 'ma-GING · nag-ka-ro-ON · mag-ka-ka-ro-ON',
    pattern: {
      frame: 'maging/naging/magiging · magkaroon/nagkaroon/magkakaroon',
      transform: 'maging → magiging',
      note: 'Use “maging” for becoming a state or role and “magkaroon” for coming to have or acquire something. “Nagkaroon” presents a change into possession, not ordinary past possession. “Na” can signal that a new state now holds.',
    },
    phrases: [
      ['maging-guro', 'Gusto kong maging guro.', 'I want to become a teacher.'],
      ['naging-tahimik', 'Naging tahimik ang silid.', 'The room became quiet.'],
      [
        'magiging-abala',
        'Magiging abala ako bukas.',
        'I will be busy tomorrow.',
      ],
      ['mayroon-na-trabaho', 'Mayroon na akong trabaho.', 'I have a job now.'],
      [
        'nagkaroon-anak',
        'Nagkaroon sila ng anak.',
        'They came to have a child / They had a child.',
      ],
      ['magkakaroon-oras', 'Magkakaroon tayo ng oras.', 'We will have time.'],
      ['pagod-na', 'Pagod na ako.', 'I am tired now.'],
    ],
    words: [
      ['maging', 'maging', 'to become'],
      ['naging', 'naging', 'became'],
      ['magiging', 'magiging', 'will become / be'],
      ['magkaroon', 'magkaroon', 'to come to have'],
      ['silid', 'silid', 'room'],
      ['abala', 'abala', 'busy'],
      ['trabaho', 'trabaho', 'work / job'],
      ['pagod', 'pagod', 'tired'],
    ],
    dialogue: [
      'Catching up about work',
      'May trabaho ka na ba?',
      'Do you have a job now?',
      'Oo, mayroon na akong trabaho.',
      'Yes, I have a job now.',
      'Kasing-init ito ng kahapon.',
      'Iyo ba iyan?',
      '“Na” marks that the new situation now holds.',
    ],
  },
  {
    id: 'location-prepositions',
    title: 'Location & movement',
    titleFil: 'Nasa kusina.',
    description:
      'Locate things precisely and describe origin, destination, and spatial relationships.',
    canDo:
      'I can say where something is and where someone is going or coming from.',
    soundTitle: 'Contrast nasa, narito, nariyan, and naroon',
    soundModel: 'Nasa. Narito. Nariyan. Naroon.',
    soundFocus:
      'Keep the ri/ro syllables distinct in narito, nariyan, and naroon. The final stress helps distinguish naroon in careful speech.',
    syllables: 'NA-sa · na-ri-TO · na-ri-YAN · na-ro-ON',
    pattern: {
      frame:
        'nasa + place · galing sa + origin · papunta/pupunta sa + destination',
      transform: 'Nasa kusina. → Pupunta sa kusina.',
      note: '“Sa” marks many locations, origins, and destinations. “Nasa” locates something; movement verbs supply the direction of travel.',
    },
    phrases: [
      [
        'nasa-kusina',
        'Nasa kusina ang pagkain.',
        'The food is in the kitchen.',
      ],
      ['narito-susi', 'Narito ang susi.', 'The key is here by me.'],
      ['nariyan-bag', 'Nariyan ang bag.', 'The bag is there by you.'],
      ['naroon-istasyon', 'Naroon ang istasyon.', 'The station is over there.'],
      [
        'tabi-bangko',
        'Sa tabi ng bangko ang botika.',
        'The pharmacy is beside the bank.',
      ],
      ['galing-opisina', 'Galing ako sa opisina.', 'I came from the office.'],
      [
        'pupunta-maynila',
        'Pupunta kami sa Maynila.',
        'We are going to Manila.',
      ],
    ],
    words: [
      ['nasa', 'nasa', 'located at'],
      ['narito', 'narito', 'here by me'],
      ['nariyan', 'nariyan', 'there by you'],
      ['naroon', 'naroon', 'over there'],
      ['kusina', 'kusina', 'kitchen'],
      ['tabi', 'tabi', 'side / beside'],
      ['galing', 'galing', 'from / came from'],
      ['pupunta', 'pupunta', 'will go / going'],
    ],
    dialogue: [
      'Looking for a pharmacy',
      'Nasaan ang botika?',
      'Where is the pharmacy?',
      'Sa tabi ng bangko.',
      'Beside the bank.',
      'Kakain tayo mamaya.',
      'Hindi pa.',
      'The location follows “sa tabi ng,” meaning beside.',
    ],
  },
  {
    id: 'recipients-benefactive',
    title: 'Giving & doing for others',
    titleFil: 'Para sa iyo ito.',
    description:
      'Name recipients and beneficiaries when giving, sending, buying, and preparing things.',
    canDo: 'I can say who receives or benefits from an action.',
    soundTitle: 'Link para sa and kay smoothly',
    soundModel: 'Para sa iyo. Kay Ana. Sa akin.',
    soundFocus:
      'Keep para sa as two clear words and use kay before one personal name. Avoid turning the vowels into English-style reduced sounds.',
    syllables: 'PA-ra sa i-YO · kay A-na · sa A-kin',
    pattern: {
      frame:
        'para sa + common noun/pronoun · para kay + name · actor-focus verb + ng theme + sa/kay/para sa recipient',
      transform: 'para sa iyo → para kay Ana',
      note: 'Use “sa” before a common noun or pronoun and “kay” before one personal name. This unit keeps the actor in focus; later units teach verbs that focus a transferred thing or a recipient.',
    },
    phrases: [
      ['para-iyo', 'Para sa iyo ito.', 'This is for you.'],
      ['ibinigay-ana', 'Nagbigay ako ng libro kay Ana.', 'I gave Ana a book.'],
      [
        'nagpadala-akin',
        'Nagpadala siya ng mensahe sa akin.',
        'He/She sent me a message.',
      ],
      [
        'ipinagluto-bisita',
        'Nagluto kami ng pansit para sa mga bisita.',
        'We cooked pancit for the guests.',
        'Para sa marks the guests as beneficiaries while the actor remains in focus.',
      ],
      [
        'bumili-lola',
        'Bumili ako ng gamot para kay Lola.',
        'I bought medicine for Grandma.',
      ],
      ['dalhin-paolo', 'Dalhin mo ito kay Paolo.', 'Bring this to Paolo.'],
      [
        'sino-bibigyan',
        'Kanino ka magbibigay ng libro?',
        'Who will you give a book to?',
        'Kanino asks which person is the recipient.',
      ],
    ],
    words: [
      ['para', 'para', 'for'],
      ['bigay', 'bigay', 'give (root)'],
      ['padala', 'padala', 'send (root)'],
      ['mensahe', 'mensahe', 'message'],
      ['bisita', 'bisita', 'guest'],
      ['gamot', 'gamot', 'medicine'],
      ['dala', 'dala', 'bring / carry (root)'],
      ['libro', 'libro', 'book'],
    ],
    dialogue: [
      'Handing someone a gift',
      'Para kanino ito?',
      'Who is this for?',
      'Para kay Ana iyan.',
      'That is for Ana.',
      'Nasa kusina ang pagkain.',
      'Alas-diyes na.',
      'Use “kay” before the personal name Ana.',
    ],
  },
  {
    id: 'locative-focus',
    title: 'Places affected by actions',
    titleFil: 'Lagyan mo ng tubig.',
    description:
      'Use common -an verbs when a place, surface, or recipient is the center of attention.',
    canDo: 'I can understand and use practical locative-focus instructions.',
    soundTitle: 'Keep -an endings audible',
    soundModel: 'Lagyan. Puntahan. Sulatan. Hugasan.',
    soundFocus:
      'The -an ending carries grammar, so do not drop it in lagyan, puntahan, sulatan, or hugasan.',
    syllables: 'lag-YAN · pun-ta-HAN · su-LA-tan · hu-GA-san',
    pattern: {
      frame:
        '-an verb + ng-form actor + ang/si focused place or recipient (+ ng theme)',
      transform: 'lagay → lagyan · punta → puntahan',
      note: 'Many -an verbs focus a location, surface, or recipient. Learn each verb with its natural participants instead of treating -an as one English preposition.',
    },
    phrases: [
      [
        'lagyan-baso',
        'Lagyan mo ng tubig ang baso.',
        'Put water in the glass.',
      ],
      [
        'puntahan-tindahan',
        'Puntahan natin ang tindahan.',
        'Let’s go to the store.',
      ],
      ['sulatan-ana', 'Sulatan mo si Ana.', 'Write to Ana.'],
      [
        'pinuntahan-palengke',
        'Pinuntahan ko ang palengke.',
        'I went to the market.',
      ],
      [
        'nilagyan-asin',
        'Nilagyan niya ng asin ang sabaw.',
        'He/She put salt in the soup.',
      ],
      [
        'tinitirhan-bahay',
        'Tinitirhan namin ang bahay na ito.',
        'We live in this house.',
      ],
      ['hugasan-plato', 'Hugasan mo ang mga plato.', 'Wash the plates.'],
    ],
    words: [
      ['lagay', 'lagay', 'put / place (root)'],
      ['punta', 'punta', 'go (root)'],
      ['sulat', 'sulat', 'write (root)'],
      ['hugasan', 'hugasan', 'wash'],
      ['baso', 'baso', 'glass'],
      ['palengke', 'palengke', 'market'],
      ['asin', 'asin', 'salt'],
      ['sabaw', 'sabaw', 'soup / broth'],
    ],
    dialogue: [
      'Preparing the table',
      'Ano ang gagawin ko sa baso?',
      'What should I do with the glass?',
      'Lagyan mo ng tubig ang baso.',
      'Put water in the glass.',
      'Bibilhin mo ba ito?',
      'Guro si Ben.',
      'The glass is the location being filled, while water follows “ng.”',
    ],
  },
  {
    id: 'requests-causatives',
    title: 'Polite requests',
    titleFil: 'Pakiabot po.',
    description:
      'Ask for an action, request help, and soften a polite negative.',
    canDo: 'I can ask for practical help without sounding abrupt.',
    soundTitle: 'Keep paki- requests light and connected',
    soundModel: 'Pakiabot po. Pakibuksan po.',
    soundFocus:
      'Attach paki- smoothly to the action in pakiabot and pakibuksan. Keep po separate and unstressed but audible.',
    syllables: 'pa-ki-a-BOT po · pa-ki-buk-SAN po',
    pattern: {
      frame: 'paki- + action + po · puwede po ba akong + action',
      transform: 'abot → pakiabot',
      note: '“Paki-” forms a practical request; “po,” “naman,” and “sana” adjust politeness and tone. A later unit distinguishes requests from magpa- causatives.',
    },
    phrases: [
      [
        'pakiabot-tubig',
        'Pakiabot po ang tubig.',
        'Please pass the water.',
        'Use this concise request when the object is clear.',
        'polite',
      ],
      [
        'pakibuksan-pinto',
        'Pakibuksan po ang pinto.',
        'Please open the door.',
        undefined,
        'polite',
      ],
      [
        'pakiusap-dahan',
        'Pakiusap, dahan-dahan lang.',
        'Please—take it slowly.',
        '“Pakiusap” makes this an earnest plea, not a neutral one-word equivalent of English “please.”',
        'polite',
      ],
      [
        'puwede-magpatulong',
        'Puwede po ba akong humingi ng tulong?',
        'May I ask for help?',
        undefined,
        'polite',
      ],
      [
        'magpapagupit',
        'Pakisulat po ang pangalan ninyo.',
        'Please write your name.',
        undefined,
        'polite',
      ],
      [
        'nagpaluto-pansit',
        'Pakihintay po sandali.',
        'Please wait a moment.',
        undefined,
        'polite',
      ],
      [
        'huwag-umalis',
        'Huwag po munang umalis.',
        'Please do not leave yet.',
        '“Muna” softens the timing to “for now/yet.”',
        'polite',
      ],
    ],
    words: [
      ['paki', 'paki-', 'please do'],
      ['abot', 'abot', 'reach / pass'],
      [
        'bukas-open',
        'bukas',
        'open (root)',
        'Final stress: bukás; contrast búkas “tomorrow.”',
      ],
      ['dahan-dahan', 'dahan-dahan', 'slowly'],
      ['tulong', 'tulong', 'help'],
      ['sulat', 'sulat', 'write (root)'],
      ['hintay', 'hintay', 'wait (root)'],
      ['muna', 'muna', 'first / for now'],
    ],
    dialogue: [
      'Asking someone to open a door',
      'Puwede po ba akong humingi ng tulong?',
      'May I ask for help?',
      'Opo. Ano po iyon?',
      'Yes. What is it?',
      'Magkakaroon tayo ng oras.',
      'Mabait na tao siya.',
      'The reply accepts the request respectfully and asks what help is needed.',
    ],
  },
  {
    id: 'thoughts-feelings',
    title: 'Thoughts, opinions & feelings',
    titleFil: 'Sa tingin ko…',
    description:
      'Share an opinion, uncertainty, affection, preference, and emotion with appropriate frames.',
    canDo: 'I can explain what I think and how I feel.',
    soundTitle: 'Keep thought frames as one rhythmic opening',
    soundModel: 'Sa tingin ko. Palagay ko.',
    soundFocus:
      'Practice sa tingin ko and palagay ko as smooth chunks, then pause briefly before the opinion that follows.',
    syllables: 'sa ti-NGIN ko · pa-la-GAY ko',
    pattern: {
      frame: 'sa tingin ko / palagay ko / akala ko + clause',
      transform: 'Tama ka. → Sa tingin ko, tama ka.',
      note: 'Opinion frames make a statement personal rather than absolute. “Akala ko” often introduces an assumption that turned out incomplete or wrong.',
    },
    phrases: [
      ['tingin-tama', 'Sa tingin ko, tama ka.', 'I think you are right.'],
      ['palagay-uulan', 'Palagay ko, uulan.', 'I think it will rain.'],
      [
        'akala-bukas',
        'Akala ko, bukas pa.',
        'I thought it was not until tomorrow.',
      ],
      ['mukhang-pagod', 'Mukhang pagod ka.', 'You look tired.'],
      ['gusto-ideya', 'Gusto ko ang ideyang iyan.', 'I like that idea.'],
      ['mahal-pamilya', 'Mahal ko ang pamilya ko.', 'I love my family.'],
      ['natatakot-aso', 'Natatakot ako sa aso.', 'I am afraid of the dog.'],
    ],
    words: [
      ['tingin', 'tingin', 'view / opinion'],
      ['palagay', 'palagay', 'opinion / supposition'],
      ['akala', 'akala', 'assumption / thought'],
      ['mukha', 'mukha', 'appearance / face'],
      ['ideya', 'ideya', 'idea'],
      ['mahal', 'mahal', 'love / dear'],
      ['takot', 'takot', 'fear'],
      ['ulan', 'ulan', 'rain'],
    ],
    dialogue: [
      'Deciding whether to go outside',
      'Lalabas ba tayo?',
      'Are we going out?',
      'Palagay ko, uulan.',
      'I think it will rain.',
      'Para kay Ana iyan.',
      'Kumain na ako.',
      '“Palagay ko” frames the rain prediction as an opinion.',
    ],
  },
  {
    id: 'relative-nominals',
    title: 'People and things in fuller phrases',
    titleFil: 'Ang taong nakapula',
    description:
      'Identify people and things with linked actions and descriptions instead of isolated labels.',
    canDo: 'I can understand and build simple who/which/that descriptions.',
    soundTitle: 'Use phrase boundaries in longer noun groups',
    soundModel: 'Ang taong nakapula ay kapatid ko.',
    soundFocus:
      'Pause after the full descriptive group, not between every word: ang taong nakapula | ay kapatid ko.',
    syllables: 'ang TA-ong na-ka-pu-LA | ay ka-pa-TID ko',
    pattern: {
      frame: 'noun + linker + action/description',
      transform: 'ang tao + nakapula → ang taong nakapula',
      note: 'The linker connects a noun to a following action or description, often covering English who, which, or that without a separate relative pronoun.',
    },
    phrases: [
      [
        'taong-nakapula',
        'Ang taong nakapula ay kapatid ko.',
        'The person wearing red is my sibling.',
      ],
      [
        'librong-binili',
        'Ito ang librong binili ko.',
        'This is the book I bought.',
      ],
      [
        'pagkaing-niluto',
        'Gusto ko ang pagkaing niluto mo.',
        'I like the food you cooked.',
      ],
      [
        'babaeng-nagsasalita',
        'Sino ang babaeng nagsasalita?',
        'Who is the woman speaking?',
      ],
      [
        'bahay-malapit',
        'Ang bahay na malapit sa dagat ay amin.',
        'The house near the sea is ours.',
      ],
      ['iyan-kailangan', 'Iyan ang kailangan ko.', 'That is what I need.'],
      [
        'taong-marunong',
        'Naghahanap kami ng taong marunong magsalita ng Tagalog.',
        'We are looking for someone who knows how to speak Tagalog.',
      ],
    ],
    words: [
      ['tao', 'tao', 'person'],
      ['nakapula', 'nakapula', 'wearing red'],
      ['babae', 'babae', 'woman'],
      ['dagat', 'dagat', 'sea'],
      ['malapit', 'malapit', 'near'],
      ['hanap', 'hanap', 'look for (root)'],
      ['salita', 'salita', 'word / speech'],
      ['binili', 'binili', 'bought'],
    ],
    dialogue: [
      'Identifying someone in a group',
      'Sino ang kapatid mo?',
      'Who is your sibling?',
      'Ang taong nakapula.',
      'The person wearing red.',
      'Hindi pa.',
      'Dalawang tiket po.',
      'The linked description identifies the person without repeating “tao.”',
    ],
  },
  {
    id: 'adverbs-connectors',
    title: 'Connected ideas',
    titleFil: 'Dahil… kaya…',
    description:
      'Add manner, frequency, alternatives, contrast, reasons, and results to connected speech.',
    canDo: 'I can connect ideas and explain why something happened.',
    soundTitle: 'Pause around idea connectors',
    soundModel: 'Pero. Dahil. Kaya.',
    soundFocus:
      'Give pero, dahil, and kaya a light boundary so the relationship between ideas stays easy to hear.',
    syllables: 'PE-ro · da-HIL · ka-YA',
    pattern: {
      frame: 'idea + pero/dahil/kaya + idea',
      transform:
        'Umuulan. Nagdala ako ng payong. → Umuulan, kaya nagdala ako ng payong.',
      note: 'Use “pero” for contrast, “dahil” before a reason, and “kaya” before a result. “At” joins and “o” offers alternatives.',
    },
    phrases: [
      [
        'maingat-magmaneho',
        'Maingat siyang magmaneho.',
        'He/She drives carefully.',
      ],
      ['araw-araw-aral', 'Araw-araw akong nag-aaral.', 'I study every day.'],
      [
        'kumain-nagkuwentuhan',
        'Kumain kami at nagkuwentuhan.',
        'We ate and chatted.',
      ],
      ['kape-o-tsaa', 'Kape o tsaa?', 'Coffee or tea?'],
      [
        'gusto-pero-wala',
        'Gusto ko, pero wala akong oras.',
        'I want to, but I do not have time.',
      ],
      [
        'umuwi-dahil-ulan',
        'Umuwi ako dahil umuulan.',
        'I went home because it was raining.',
      ],
      [
        'maulan-kaya-payong',
        'Maulan, kaya nagdala ako ng payong.',
        'It was rainy, so I brought an umbrella.',
      ],
    ],
    words: [
      ['at', 'at', 'and'],
      ['o', 'o', 'or'],
      ['pero', 'pero', 'but'],
      ['dahil', 'dahil', 'because'],
      ['kaya', 'kaya', 'so / therefore'],
      ['maingat', 'maingat', 'careful'],
      ['payong', 'payong', 'umbrella'],
      ['araw-araw', 'araw-araw', 'every day'],
    ],
    dialogue: [
      'Explaining a change of plans',
      'Bakit ka umuwi?',
      'Why did you go home?',
      'Umuwi ako dahil umuulan.',
      'I went home because it was raining.',
      'Para sa iyo ito.',
      'Pakiabot po.',
      '“Dahil” introduces the reason for going home.',
    ],
  },
  {
    id: 'agreement-doubt',
    title: 'Agreement, doubt & refusal',
    titleFil: 'Siguro. Baka.',
    description:
      'Agree, disagree, refuse, and express different levels of certainty without sounding abrupt.',
    canDo:
      'I can respond with agreement, uncertainty, or a polite disagreement.',
    soundTitle: 'Let small response words carry natural intonation',
    soundModel: 'Talaga. Siguro. Baka.',
    soundFocus:
      'Practice talaga as three full syllables and keep baka distinct from bakit. Intonation helps turn “Talaga?” into a genuine question.',
    syllables: 'ta-la-GA · si-GU-ro · ba-KA',
    pattern: {
      frame: 'oo/hindi + statement · huwag + command · siguro/baka + clause',
      transform: 'Darating siya. → Siguro darating siya.',
      note: '“Siguro,” “baka,” and formal “marahil” mark uncertainty with different registers. “Huwag” negates a command; it is not interchangeable with “hindi.”',
    },
    phrases: [
      ['oo-tama', 'Oo, tama ka.', 'Yes, you are right.'],
      ['hindi-sang-ayon', 'Hindi ako sang-ayon.', 'I do not agree.'],
      ['huwag-muna', 'Huwag muna.', 'Do not do it yet / Not for now.'],
      ['talaga', 'Talaga?', 'Really?'],
      [
        'siyanga',
        'Siyangâ.',
        'That is right / That is true.',
        'A textbook/formal idiom; everyday speech more often uses “Oo nga.”',
        'formal',
      ],
      [
        'siguro-darating',
        'Siguro darating siya.',
        'He/She will probably come.',
      ],
      ['baka-mahuli', 'Baka mahuli tayo.', 'We might be late.'],
    ],
    words: [
      ['oo', 'oo', 'yes'],
      ['hindi', 'hindi', 'no / not'],
      ['huwag', 'huwag', 'do not'],
      ['talaga', 'talaga', 'really'],
      ['siyanga', 'siyangâ', 'that is right / that is true'],
      ['siguro', 'siguro', 'probably / perhaps'],
      ['baka', 'baka', 'maybe / might'],
      ['sang-ayon', 'sang-ayon', 'in agreement'],
    ],
    dialogue: [
      'Wondering whether a friend will arrive',
      'Darating ba si Leo?',
      'Will Leo come?',
      'Siguro, pero baka mahuli siya.',
      'Probably, but he might be late.',
      'Akin ito.',
      'Nasa kusina ang pagkain.',
      'The answer avoids false certainty and then adds a contrasting possibility.',
    ],
  },
  {
    id: 'word-building',
    title: 'Roots & person nouns',
    titleFil: 'Sulat → manunulat',
    description:
      'Recognize familiar roots inside common words for people and occupations.',
    canDo: 'I can use a known root to infer several useful person nouns.',
    soundTitle: 'Find the root inside longer words',
    soundModel: 'Sulat. Manunulat. Manggagawa.',
    soundFocus:
      'Say the root first, then the person noun. Preserve every repeated syllable in manunulat and the nasal sound in manggagawa.',
    syllables: 'SU-lat · ma-nu-nu-LAT · mang-ga-GA-wa',
    pattern: {
      frame: 'root + person-forming pattern = related person noun',
      transform: 'sulat → manunulat',
      note: 'A Tagalog root can appear inside several related words. Treat forms such as manunulat and manggagawa as whole useful words while learning to notice their roots; one affix does not always have one English translation.',
    },
    phrases: [
      [
        'sumusulat-liham',
        'Sulat ang ugat ng manunulat.',
        'Sulat is the root of manunulat.',
      ],
      [
        'manunulat-kapatid',
        'Manunulat ang kapatid ko.',
        'My sibling is a writer.',
      ],
      [
        'basahin-babasahin',
        'Gawa ang ugat ng manggagawa.',
        'Gawa is the root of manggagawa.',
      ],
      [
        'masipag-manggagawa',
        'Masipag ang manggagawa.',
        'The worker is hardworking.',
      ],
      ['nakahiga-bata', 'Tagapagturo namin si Ana.', 'Ana is our instructor.'],
      [
        'nakasara-tindahan',
        'Magsasaka ang tatay niya.',
        'His/Her father is a farmer.',
      ],
      ['nagkita-kita', 'Mananayaw si Rosa.', 'Rosa is a dancer.'],
    ],
    words: [
      ['ugat', 'ugat', 'root'],
      ['sulat', 'sulat', 'write / letter (root)'],
      ['manunulat', 'manunulat', 'writer'],
      ['gawa', 'gawa', 'make / work (root)'],
      ['manggagawa', 'manggagawa', 'worker'],
      ['tagapagturo', 'tagapagturo', 'instructor'],
      ['magsasaka', 'magsasaka', 'farmer'],
      ['mananayaw', 'mananayaw', 'dancer'],
    ],
    dialogue: [
      'Talking about a sibling’s work',
      'Ano ang trabaho ng kapatid mo?',
      'What is your sibling’s job?',
      'Manunulat ang kapatid ko.',
      'My sibling is a writer.',
      'Baka mahuli tayo.',
      'Kape o tsaa?',
      'The root sulat is visible inside manunulat, a person associated with writing.',
    ],
  },
  {
    id: 'spoken-filipino',
    title: 'Everyday spoken Filipino',
    titleFil: 'Sandali lang.',
    description:
      'Understand common contractions, conversational pacing, borrowed words, and register shifts.',
    canDo:
      'I can follow common casual speech without losing the careful forms.',
    soundTitle: 'Connect words without erasing their meaning',
    soundModel: 'Sandali lang. Teka muna. Nasaan ’yung susi?',
    soundFocus:
      'Conversational forms such as ’di and ’yung shorten common words. Learn the full forms first, then recognize the shorter rhythm.',
    syllables: 'san-da-LI lang · TE-ka MU-na · na-sa-AN ’yung SU-si',
    pattern: {
      frame: 'careful form ↔ common conversational form',
      transform: 'hindi → ’di · iyong → ’yung',
      note: 'Contractions are normal in casual Filipino but not required in careful speech. Taglish borrowing is common; register and audience still matter.',
    },
    phrases: [
      ['sandali-lang', 'Sandali lang.', 'Just a moment.'],
      ['teka-muna', 'Teka muna.', 'Wait a second.', undefined, 'casual'],
      [
        'nasaan-yung-susi',
        "Nasaan 'yung susi?",
        'Where is the key?',
        '“’Yung” is a common conversational reduction of “iyong”; in colloquial speech it often functions as a determiner.',
        'casual',
      ],
      ['diyan-lang', 'Diyan ka lang.', 'Just stay there.', undefined, 'casual'],
      [
        'di-ko-alam',
        "'Di ko alam.",
        'I do not know.',
        '“’Di” is a common contraction of “hindi.”',
        'casual',
      ],
      [
        'kumain-ka-na',
        'Kumain ka na?',
        'Have you eaten?',
        'In casual speech, intonation can carry the yes/no question even when “ba” is omitted.',
        'casual',
      ],
      [
        'okay-lang',
        'Okay lang ako.',
        'I am okay.',
        '“Okay” is an ordinary borrowed word in contemporary Filipino.',
        'Taglish',
      ],
    ],
    words: [
      ['sandali', 'sandali', 'moment'],
      ['teka', 'teka', 'wait'],
      ['yung', "'yung", 'the / that (casual marker)'],
      ['di', "'di", 'not (casual)'],
      ['alam', 'alam', 'know'],
      ['lang', 'lang', 'only / just'],
      ['muna', 'muna', 'first / for now'],
      ['okay', 'okay', 'okay'],
    ],
    dialogue: [
      'Looking for a key at home',
      "Nasaan 'yung susi?",
      'Where is the key?',
      'Diyan lang sa mesa.',
      'Right there on the table.',
      'Sa tingin ko, tama ka.',
      'Dalawang tiket po.',
      'This is a casual exchange; use the careful forms when clarity or formality calls for them.',
    ],
  },
  {
    id: 'shopping-colors',
    title: 'Shopping, colors & fit',
    titleFil: 'Kukunin ko ito.',
    description:
      'Ask about color, size, fit, price, and complete a simple store interaction.',
    canDo: 'I can compare, try on, and buy an item politely.',
    soundTitle: 'Keep color and size words clear in questions',
    soundModel: 'Kulay. Maliit. Sukatin.',
    soundFocus:
      'Practice kulay, maliit, and sukatin with full vowels. In “mas maliit,” keep mas separate from the adjective.',
    syllables: 'ku-LAY · ma-li-IT · su-KA-tin',
    pattern: {
      frame: 'May mas + adjective + po ba nito? · Kukunin ko + item',
      transform: 'maliit → mas maliit',
      note: 'Use “nito” when asking for another version of the item at hand. “Kukunin ko ito” is a natural way to commit to buying it.',
    },
    phrases: [
      ['anong-kulay', 'Anong kulay ang gusto mo?', 'What color do you want?'],
      [
        'mas-maliit',
        'May mas maliit po ba nito?',
        'Do you have this in a smaller size?',
      ],
      ['kasya-akin', 'Kasya ito sa akin.', 'This fits me.'],
      ['masyadong-mahal', 'Masyadong mahal.', 'It is too expensive.'],
      ['mas-mura-iyon', 'Mas mura ba iyon?', 'Is that one cheaper?'],
      ['puwede-sukatin', 'Puwede ko bang sukatin?', 'May I try it on?'],
      ['kukunin-ito', 'Kukunin ko ito.', 'I will take this.'],
    ],
    words: [
      ['kulay', 'kulay', 'color'],
      ['pula', 'pula', 'red'],
      ['asul', 'asul', 'blue'],
      ['puti', 'puti', 'white'],
      ['itim', 'itim', 'black'],
      ['maliit', 'maliit', 'small'],
      ['kasya', 'kasya', 'fits / enough'],
      ['sukatin', 'sukatin', 'try on / measure'],
    ],
    dialogue: [
      'Trying on a shirt',
      'Kasya po ba?',
      'Does it fit?',
      'Opo. Kukunin ko ito.',
      'Yes. I will take this.',
      'Hindi ako sang-ayon.',
      'Nasa kusina ang pagkain.',
      'The customer confirms the fit and completes the purchase clearly.',
    ],
  },
  {
    id: 'food-cooking',
    title: 'Market & cooking',
    titleFil: 'Kain na tayo!',
    description:
      'Buy ingredients, follow a short recipe, and share a meal with natural hosting language.',
    canDo:
      'I can shop for ingredients and understand basic cooking instructions.',
    soundTitle: 'Hear action boundaries in instructions',
    soundModel: 'Hiwain. Igisa. Pakuluan.',
    soundFocus:
      'Keep hiwain, igisa, lagyan, and pakuluan distinct. In “nang sampung minuto,” nang introduces the duration or manner.',
    syllables: 'hi-wa-IN · i-gi-SA · pa-ku-lu-AN',
    pattern: {
      frame: 'command verb + focused ingredient · nang + duration',
      transform: 'hiwa → hiwain · kulo → pakuluan',
      note: 'Recipe instructions often use patient- or location-focused commands because the ingredient or container is already central. “Nang” can introduce a duration.',
    },
    phrases: [
      [
        'kalahating-kilo',
        'Kalahating kilo ng kamatis.',
        'Half a kilo of tomatoes.',
      ],
      ['hiwain-sibuyas', 'Hiwain ang sibuyas.', 'Slice the onion.'],
      ['igisa-bawang', 'Igisa ang bawang.', 'Sauté the garlic.'],
      ['lagyan-asin', 'Lagyan ng asin.', 'Add salt.'],
      [
        'pakuluan-sampu',
        'Pakuluan nang sampung minuto.',
        'Boil it for ten minutes.',
      ],
      ['kain-na-tayo', 'Kain na tayo!', 'Let’s eat!'],
      ['masarap-luto', 'Masarap ang luto mo.', 'Your cooking is delicious.'],
    ],
    words: [
      ['kamatis', 'kamatis', 'tomato'],
      ['sibuyas', 'sibuyas', 'onion'],
      ['bawang', 'bawang', 'garlic'],
      ['asin', 'asin', 'salt'],
      ['hiwa', 'hiwa', 'slice / cut'],
      ['gisa', 'gisa', 'sauté'],
      ['kulo', 'kulo', 'boil'],
      ['minuto', 'minuto', 'minute'],
    ],
    dialogue: [
      'Buying tomatoes at a market',
      'Ilang kilo ng kamatis ang kailangan ninyo?',
      'How many kilos of tomatoes do you need?',
      'Kalahating kilo po.',
      'Half a kilo, please.',
      'Kukunin ko ito.',
      'Baka mahuli tayo.',
      'The answer uses a practical market quantity and keeps the exchange polite.',
    ],
  },
  {
    id: 'home-family',
    title: 'Home, family & guests',
    titleFil: 'Tuloy po kayo.',
    description:
      'Talk about family relationships, chores, visitors, and a shared evening at home.',
    canDo: 'I can welcome a guest and describe household routines.',
    soundTitle: 'Practice respectful doorway expressions',
    soundModel: 'Tao po! Tuloy po kayo.',
    soundFocus:
      'In “Tao po!” and “Tuloy po kayo,” keep po light but audible. These expressions carry cultural and social meaning as complete chunks.',
    syllables: 'TA-o po · tu-LOY po ka-YO',
    pattern: {
      frame:
        'action + tayo · paki- + household action · respectful guest phrase',
      transform: 'Ayusin ang mesa. → Pakiayos ang mesa.',
      note: 'Household language combines inclusive “tayo,” everyday actor-focus, and polite requests. “Tao po!” announces a visitor at a home rather than asking whether someone is human.',
    },
    phrases: [
      [
        'nakatatandang-kapatid',
        'Ito ang nakatatanda kong kapatid.',
        'This is my older sibling.',
      ],
      ['maglinis-bahay', 'Maglinis tayo ng bahay.', 'Let’s clean the house.'],
      [
        'naghuhugas-pinggan',
        'Naghuhugas ako ng pinggan.',
        'I am washing dishes.',
      ],
      ['pakiayos-mesa', 'Pakiayos ang mesa.', 'Please set the table.'],
      [
        'tao-po',
        'Tao po!',
        'Hello! Is anyone home?',
        'A customary visitor’s call at a doorway.',
        'polite',
      ],
      ['tuloy-kayo', 'Tuloy po kayo.', 'Please come in.', undefined, 'polite'],
      [
        'pamilya-nagkuwentuhan',
        'Nagkuwentuhan ang pamilya pagkatapos kumain.',
        'The family chatted after eating.',
      ],
    ],
    words: [
      ['pamilya', 'pamilya', 'family'],
      ['nakatatanda', 'nakatatanda', 'older'],
      ['linis', 'linis', 'clean (root)'],
      ['hugas', 'hugas', 'wash (root)'],
      ['pinggan', 'pinggan', 'dish / plate'],
      ['mesa', 'mesa', 'table'],
      ['bisita', 'bisita', 'guest'],
      ['tuloy', 'tuloy', 'continue / come in'],
    ],
    dialogue: [
      'Arriving at someone’s home',
      'Tao po!',
      'Hello! Is anyone home?',
      'Tuloy po kayo.',
      'Please come in.',
      'Kain na tayo!',
      'Mas mura ba iyon?',
      'These are conventional, respectful doorway expressions in many Filipino homes.',
    ],
  },
  {
    id: 'school-work',
    title: 'School & work',
    titleFil: 'May pulong ako.',
    description:
      'Handle schedules, questions, assignments, meetings, documents, and project updates.',
    canDo: 'I can participate in a basic school or work exchange.',
    soundTitle: 'Keep borrowed words in Filipino rhythm',
    soundModel: 'Proyekto. Dokumento.',
    soundFocus:
      'Words such as proyekto and dokumento are borrowed but follow Filipino syllable rhythm. Keep every vowel audible.',
    syllables: 'pro-YEK-to · do-ku-MEN-to',
    pattern: {
      frame:
        'may + school/work item + possessor/time · aspect-marked verb + actor + ang/ng work item',
      transform: 'May pulong. → May pulong ako mamaya.',
      note: 'Borrowed vocabulary combines naturally with Tagalog grammar. Add time and participants using familiar particles and markers.',
    },
    phrases: [
      ['anong-oras-klase', 'Anong oras ang klase?', 'What time is the class?'],
      ['takdang-aralin', 'May takdang-aralin kami.', 'We have homework.'],
      [
        'maaari-magtanong',
        'Maaari po ba akong magtanong?',
        'May I ask a question?',
        undefined,
        'formal',
      ],
      ['pulong-mamaya', 'May pulong ako mamaya.', 'I have a meeting later.'],
      ['trabaho-bahay', 'Nagtatrabaho ako mula sa bahay.', 'I work from home.'],
      [
        'ipapadala-dokumento',
        'Ipapadala ko ang dokumento.',
        'I will send the document.',
      ],
      [
        'natapos-proyekto',
        'Natapos na namin ang proyekto.',
        'We have finished the project.',
      ],
    ],
    words: [
      ['klase', 'klase', 'class'],
      ['takdang-aralin', 'takdang-aralin', 'homework'],
      ['tanong', 'tanong', 'question'],
      ['pulong', 'pulong', 'meeting'],
      ['opisina', 'opisina', 'office'],
      ['dokumento', 'dokumento', 'document'],
      ['proyekto', 'proyekto', 'project'],
      ['padala', 'padala', 'send (root)'],
    ],
    dialogue: [
      'Checking on a project',
      'Natapos na ba ninyo ang proyekto?',
      'Have you finished the project?',
      'Opo, natapos na namin.',
      'Yes, we have finished it.',
      'Tuloy po kayo.',
      'Palagay ko, uulan.',
      '“Ninyo” is respectful singular or plural “you”; “namin” means “we” excluding the listener and is not a politeness form.',
    ],
  },
  {
    id: 'travel-health',
    title: 'Travel & health problems',
    titleFil: 'Saan ang botika?',
    description:
      'Solve transport, accommodation, illness, pharmacy, and lost-document problems.',
    canDo: 'I can get help during a common travel or health problem.',
    soundTitle: 'Prioritize clarity in high-stakes phrases',
    soundModel: 'Sakayan. Bakante. Pakiramdam.',
    soundFocus:
      'Slow down enough to keep sakayan, bakante, pakiramdam, botika, and pasaporte clear. In urgent situations, short complete phrases are best.',
    syllables: 'sa-KA-yan · ba-KAN-te · pa-ki-ram-DAM',
    pattern: {
      frame: 'saan ang + place · may + symptom · nawala ang + item',
      transform: 'May lagnat ako. → Masama ang pakiramdam ko.',
      note: 'Use direct location and state frames when you need help. “Nawala ang…” reports that an item was lost; “Naliligaw ako” reports that you cannot find your way.',
    },
    phrases: [
      ['sakayan-bus', 'Saan ang sakayan ng bus?', 'Where is the bus stop?'],
      ['tiket-cebu', 'Isang tiket papuntang Cebu.', 'One ticket to Cebu.'],
      [
        'bakanteng-kuwarto',
        'May bakanteng kuwarto ba?',
        'Is there an available room?',
      ],
      ['masama-pakiramdam', 'Masama ang pakiramdam ko.', 'I feel unwell.'],
      ['may-lagnat', 'May lagnat ako.', 'I have a fever.'],
      [
        'malapit-botika',
        'Saan ang pinakamalapit na botika?',
        'Where is the nearest pharmacy?',
      ],
      ['nawala-pasaporte', 'Nawala ang pasaporte ko.', 'My passport is lost.'],
    ],
    words: [
      ['sakayan', 'sakayan', 'stop / boarding place'],
      ['papunta', 'papunta', 'headed to'],
      ['bakante', 'bakante', 'available / vacant'],
      ['kuwarto', 'kuwarto', 'room'],
      ['pakiramdam', 'pakiramdam', 'feeling / condition'],
      ['lagnat', 'lagnat', 'fever'],
      ['botika', 'botika', 'pharmacy'],
      ['pasaporte', 'pasaporte', 'passport'],
    ],
    dialogue: [
      'Asking for a pharmacy while ill',
      'Masama ang pakiramdam ko. Saan ang pinakamalapit na botika?',
      'I feel unwell. Where is the nearest pharmacy?',
      'Sa tabi po ng ospital.',
      'Beside the hospital.',
      'May pulong ako mamaya.',
      'Kape o tsaa?',
      'The reply gives a short location and preserves respectful “po.”',
    ],
  },
  {
    id: 'stories-capstone',
    title: 'Stories & conversation capstone',
    titleFil: 'Ikukuwento ko.',
    description:
      'Connect time, cause, sequence, opinion, and condition across a short personal story.',
    canDo:
      'I can tell a connected story and sustain a multi-turn conversation.',
    soundTitle: 'Speak in meaningful phrases, not one long rush',
    soundModel: 'Kahapon. Pumunta ako. Habang naglalakad.',
    soundFocus:
      'Group a story into short thought units. Pause after time openers and connectors so listeners can follow the sequence.',
    syllables: 'ka-HA-pon | pu-mun-TA a-KO · HA-bang nag-LA-la-KAD',
    pattern: {
      frame: 'time opener + event + connector + result/opinion',
      transform:
        'Naglalakad ako. Umulan. Umuwi ako. → Habang naglalakad ako, umulan, kaya umuwi ako.',
      note: 'Connected storytelling recycles aspect, focus, linkers, and time clauses. Accuracy grows by retelling the same event with new detail rather than memorizing one script.',
    },
    phrases: [
      [
        'noong-bata',
        'Noong bata ako, nakatira kami sa California.',
        'When I was a child, we lived in California.',
      ],
      [
        'kahapon-pumunta',
        'Kahapon, pumunta ako sa palengke.',
        'Yesterday, I went to the market.',
      ],
      [
        'habang-naglalakad',
        'Habang naglalakad ako, umulan.',
        'While I was walking, it rained.',
      ],
      [
        'pagdating-nagsimula',
        'Pagdating namin, nagsimula na ang programa.',
        'When we arrived, the program had already started.',
      ],
      [
        'palagay-mahalaga',
        'Sa palagay ko, mahalaga ito dahil nakatutulong ito.',
        'In my opinion, this is important because it helps.',
      ],
      [
        'kung-may-oras',
        'Kung may oras ako, babalik ako.',
        'If I have time, I will return.',
      ],
      [
        'ikukuwento-nangyari',
        'Ngayon, ikukuwento ko ang nangyari.',
        'Now, I will tell what happened.',
      ],
    ],
    words: [
      ['noong', 'noong', 'when / during (past)'],
      ['kahapon', 'kahapon', 'yesterday'],
      ['habang', 'habang', 'while'],
      ['pagdating', 'pagdating', 'upon arrival'],
      ['nagsimula', 'nagsimula', 'started'],
      ['mahalaga', 'mahalaga', 'important'],
      ['kung', 'kung', 'if'],
      ['kuwento', 'kuwento', 'story / tell (root)'],
    ],
    dialogue: [
      'Retelling a rainy afternoon',
      'Ano ang nangyari kahapon?',
      'What happened yesterday?',
      'Habang naglalakad ako, umulan, kaya umuwi ako.',
      'While I was walking, it rained, so I went home.',
      'Kukunin ko ito.',
      'Tao po!',
      'The reply links background, event, and result into one understandable sequence.',
    ],
  },
  {
    id: 'ang-ng-marking',
    title: 'Marking the main participant',
    titleFil: 'Ang babae at ang isda',
    description:
      'Contrast ang and ng when the actor or affected thing is the center of the message.',
    canDo:
      'I can follow who acts, what is affected, and which participant the sentence highlights.',
    soundTitle: 'Hear short markers without dropping them',
    soundModel: 'Bumili ang babae ng isda. Binasa ni Ana ang libro.',
    soundFocus:
      'Keep ang, ng, si, and ni short but audible. These small markers carry essential information about each participant.',
    syllables: 'bu-mi-LI ang ba-BA-e ng is-DA · bi-NA-sa ni A-na ang lib-RO',
    pattern: {
      frame:
        'actor-focus verb + ang/si actor + ng patient · patient-focus verb + ng/ni actor + ang patient',
      transform: 'Bumili ang babae ng isda. → Binili ng babae ang isda.',
      note: 'Ang marks the focused common-noun phrase; ng marks a nonfocused common-noun participant. Si and ni fill parallel roles before one personal name. These markers are not simple copies of English articles.',
    },
    phrases: [
      [
        'bumili-babae-isda',
        'Bumili ang babae ng isda.',
        'The woman bought a fish. (woman in focus)',
      ],
      [
        'binili-babae-isda',
        'Binili ng babae ang isda.',
        'The woman bought the fish. (fish in focus)',
      ],
      [
        'kumain-bata-mangga',
        'Kumain ang bata ng mangga.',
        'The child ate a mango. (child in focus)',
      ],
      [
        'kinain-bata-mangga',
        'Kinain ng bata ang mangga.',
        'The child ate the mango. (mango in focus)',
      ],
      ['nagbasa-ana', 'Nagbasa si Ana ng libro.', 'Ana read a book.'],
      ['binasa-ana', 'Binasa ni Ana ang libro.', 'Ana read the book.'],
      ['ano-binili', 'Ano ang binili mo?', 'What did you buy?'],
    ],
    words: [
      ['ang-marker', 'ang', 'focused common-noun marker'],
      ['ng-marker', 'ng', 'nonfocused common-noun marker'],
      ['si-marker', 'si', 'focused personal-name marker'],
      ['ni-marker', 'ni', 'nonfocused personal-name marker'],
      ['babae', 'babae', 'woman'],
      ['libro', 'libro', 'book'],
      ['bili', 'bili', 'buy (root)'],
      [
        'basa',
        'basa',
        'read (root)',
        'Initial stress: bása “read”; contrast basâ “wet.”',
      ],
    ],
    dialogue: [
      'Asking what Ana read',
      'Ano ang binasa ni Ana?',
      'What did Ana read?',
      'Binasa ni Ana ang libro.',
      'Ana read the book.',
      'Nagbasa si Ana ng libro.',
      'Kumain ang bata ng mangga.',
      'The question and reply keep the reading material in focus while ni marks Ana as the actor.',
    ],
  },
  {
    id: 'when-time-clauses',
    title: 'When things happen',
    titleFil: 'Kailan ka darating?',
    description:
      'Distinguish question kailan, past nang/noong, and present, future, or conditional kung/kapag.',
    canDo: 'I can ask when something happens and connect two events in time.',
    soundTitle: 'Pause lightly between time and event clauses',
    soundModel: 'Kailan ka darating? Kapag may oras ako, tatawag ako.',
    soundFocus:
      'Keep kailan as three clear syllables. A light pause after a time clause makes longer sentences easier to understand.',
    syllables:
      'ka-i-LAN ka da-ra-TING · ka-PAG may O-ras a-KO | ta-TA-wag a-KO',
    pattern: {
      frame:
        'kailan + question · nang/noong + past clause · kung + uncertain/hypothetical condition · kapag + expected/repeated when-condition · habang/bago/pagkatapos + time relation',
      transform:
        'May oras ako. Tatawag ako. → Kapag may oras ako, tatawag ako.',
      note: 'Kailan asks when. Nang or noong places an event in past time. Kung introduces an uncertain or hypothetical “if” condition; kapag introduces an expected or repeated “when/whenever” condition. Habang marks overlapping action; bago and pagkatapos order events.',
    },
    phrases: [
      ['kailan-darating', 'Kailan ka darating?', 'When will you arrive?'],
      [
        'nang-dumating',
        'Nang dumating siya, kumakain kami.',
        'When he/she arrived, we were eating.',
      ],
      [
        'kapag-oras-tawag',
        'Kapag may oras ako, tatawag ako.',
        'When I have time, I will call.',
      ],
      [
        'noong-lunes-trabaho',
        'Noong Lunes, nagtrabaho ako.',
        'Last Monday, I worked.',
      ],
      [
        'habang-kumakain',
        'Habang kumakain kami, dumating siya.',
        'While we were eating, he/she arrived.',
      ],
      [
        'kung-aalis',
        'Kung aalis ka, sasama ako.',
        'If you leave, I will go with you.',
      ],
      [
        'pagkatapos-klase',
        'Pagkatapos ng klase, uuwi ako.',
        'After class, I will go home.',
      ],
    ],
    words: [
      ['kailan', 'kailan', 'when (question)'],
      ['kapag', 'kapag', 'when / whenever'],
      ['noong', 'noong', 'when / during (past)'],
      ['habang', 'habang', 'while'],
      ['bago-time', 'bago', 'before'],
      ['pagkatapos', 'pagkatapos', 'after / afterward'],
      ['nang-time', 'nang', 'when (past event)'],
      ['kung', 'kung', 'if / when'],
    ],
    dialogue: [
      'Arranging a call',
      'Kailan ka tatawag?',
      'When will you call?',
      'Kapag may oras ako, tatawag ako.',
      'When I have time, I will call.',
      'Noong Lunes, nagtrabaho ako.',
      'Pagkatapos ng klase, uuwi ako.',
      'Kapag introduces the time or condition; the second clause states what will happen then.',
    ],
  },
  {
    id: 'clock-calendar',
    title: 'Clock time & calendar dates',
    titleFil: 'Alas-siyete ng umaga.',
    description:
      'Read common clock times, name a day, and place an event on a calendar date.',
    canDo: 'I can ask the time and understand a simple day, hour, or date.',
    soundTitle: 'Keep each clock group in one clear rhythm',
    soundModel: 'Alas-diyes. Alas-siyete ng umaga.',
    soundFocus:
      'Keep alas light, preserve the hour word, and pronounce every vowel in siyete and umaga.',
    syllables: 'a-las DIYES · a-las si-YE-te ng u-MA-ga',
    pattern: {
      frame: 'Anong oras...? · alas-[hour] ng [part of day] · sa [day/date]',
      transform: 'alas-siyete + umaga → alas-siyete ng umaga',
      note: 'Within a clock phrase, ng links the hour to umaga, hapon, or gabi. Use nang before the entire clock phrase when it modifies a verb, and sa before a day or date.',
    },
    phrases: [
      ['anong-oras-ngayon', 'Anong oras na?', 'What time is it?'],
      ['alas-diyes-na', 'Alas-diyes na.', 'It is ten o’clock now.'],
      [
        'alas-siyete-almusal',
        'Alas-siyete ng umaga ang almusal.',
        'Breakfast is at seven in the morning.',
      ],
      [
        'uuwi-alas-singko',
        'Uuwi ako nang alas-singko ng hapon.',
        'I will go home at five in the afternoon.',
        'Nang introduces the time of the action; ng remains inside the clock expression.',
      ],
      [
        'lunes-magkikita',
        'Sa Lunes tayo magkikita.',
        'We will meet on Monday.',
      ],
      ['anong-petsa', 'Anong petsa ngayon?', 'What is today’s date?'],
      [
        'ikasampu-setyembre-clock',
        'Sa ikasampu ng Setyembre tayo aalis.',
        'We will leave on September tenth.',
        'The native ordinal date is useful in careful speech.',
      ],
    ],
    words: [
      ['oras', 'oras', 'clock time / hour'],
      [
        'alas-marker',
        'alas',
        'clock-hour marker',
        'Used before most hours; one o’clock is ala-una.',
      ],
      ['diyes', 'diyes', 'ten (clock form)'],
      ['siyete', 'siyete', 'seven (clock form)'],
      ['singko', 'singko', 'five (clock form)'],
      ['lunes', 'Lunes', 'Monday'],
      ['setyembre', 'Setyembre', 'September'],
      ['petsa', 'petsa', 'calendar date'],
    ],
    dialogue: [
      'Confirming a Monday meeting',
      'Anong oras tayo magkikita sa Lunes?',
      'What time will we meet on Monday?',
      'Alas-siyete ng umaga.',
      'At seven in the morning.',
      'Alas-singko ng hapon.',
      'Sa ikasampu ng Setyembre tayo aalis.',
      'The reply gives the hour first, followed by ng and the part of day.',
    ],
  },
  {
    id: 'causatives',
    title: 'Causatives & arranged services',
    titleFil: 'Nagpaayos ako.',
    description:
      'Describe causing or arranging an action, including common personal services.',
    canDo: 'I can say that I arranged for someone else to perform an action.',
    soundTitle: 'Preserve the root stress after magpa-',
    soundModel: 'Magpagupit. Nagpaayos. Magpapalinis.',
    soundFocus:
      'Keep magpa- light and preserve the root stress in gupit, ayos, and linis. The contemplated form adds another pa syllable.',
    syllables: 'mag-pa-gu-PIT · nag-pa-A-yos · mag-pa-pa-LI-nis',
    pattern: {
      frame: 'magpa- + root + affected thing · sa/kay + person asked to act',
      transform: 'ayos → magpaayos',
      note: 'Magpa- presents the subject as the person who causes or arranges the action. It is not interchangeable with the request prefix paki-, and participant marking should be learned with each verb.',
    },
    phrases: [
      [
        'nagpagupit-buhok',
        'Nagpagupit siya ng buhok.',
        'He/She had a haircut.',
      ],
      [
        'magpapagupit-bukas',
        'Magpapagupit ako bukas.',
        'I will get a haircut tomorrow.',
      ],
      [
        'nagpaluto-adobo',
        'Nagpaluto kami ng adobo.',
        'We had someone cook adobo.',
      ],
      [
        'magpapalinis-bahay',
        'Magpapalinis kami ng bahay.',
        'We will have the house cleaned.',
      ],
      [
        'nagpaayos-bisikleta',
        'Nagpaayos siya ng bisikleta.',
        'He/She had the bicycle repaired.',
      ],
      [
        'nagpagamot-kahapon',
        'Nagpagamot siya kahapon.',
        'He/She sought medical treatment yesterday.',
      ],
      [
        'nagpabasa-guro',
        'Nagpabasa ang guro sa mga bata ng libro.',
        'The teacher had the children read a book.',
        'The guro is the causer; sa mga bata identifies the people asked to read.',
      ],
    ],
    words: [
      ['magpagupit', 'magpagupit', 'get a haircut / have hair cut'],
      ['magpaluto', 'magpaluto', 'have food cooked'],
      ['magpalinis', 'magpalinis', 'have something cleaned'],
      ['magpaayos', 'magpaayos', 'have something repaired or arranged'],
      ['magpagamot', 'magpagamot', 'seek medical treatment'],
      ['magpabasa', 'magpabasa', 'have someone read'],
      ['buhok', 'buhok', 'hair'],
      ['bisikleta', 'bisikleta', 'bicycle'],
    ],
    dialogue: [
      'Planning a haircut',
      'Magpapagupit ka ba bukas?',
      'Will you get a haircut tomorrow?',
      'Oo, magpapagupit ako bukas.',
      'Yes, I will get a haircut tomorrow.',
      'Hindi, nagpagupit ako kahapon.',
      'Nagpaayos ako ng bisikleta.',
      'The subject arranges the service and is not necessarily the person who physically performs it.',
    ],
  },
  {
    id: 'derived-result-nouns',
    title: 'Derived nouns & naka- states',
    titleFil: 'Ito ang babasahin. Nakasara.',
    description:
      'Use several high-frequency derived forms as nouns, then describe visible states and conditions with naka-.',
    canDo:
      'I can identify something to read or do and describe its current state.',
    soundTitle: 'Keep the root audible in longer derived forms',
    soundModel: 'Babasahin. Nakahiga. Nakasara.',
    soundFocus:
      'Keep all four syllables in noun babasahín, with final stress. The verbal homograph babasáhin has penultimate stress. In naka- state words, keep naka- light and preserve the root stress.',
    syllables: 'ba-ba-sa-HIN · na-ka-hi-GA · na-ka-sa-RA',
    pattern: {
      frame: 'ang/may/ito + familiar derived form · naka- + root for a state',
      transform: 'sara → nakasara',
      note: 'Naka- plus a root describes a state or condition here, not grammatical tense. Babasahin, gawain, and inumin are learned in noun-licensing contexts; -in is not a universal noun-forming suffix.',
    },
    phrases: [
      [
        'ito-babasahin',
        'Ito ang babasahin natin.',
        'This is our reading material.',
        'Here, final stress and the ang frame mark noun babasahín, “reading material”; penultimate-stress babasáhin is the verbal homograph.',
      ],
      [
        'maraming-gawain',
        'Marami akong gawain ngayon.',
        'I have many tasks today.',
      ],
      ['may-inumin', 'May inumin sa mesa.', 'There is a drink on the table.'],
      ['nakahiga-bata', 'Nakahiga ang bata.', 'The child is lying down.'],
      [
        'nakasara-tindahan',
        'Nakasara ang tindahan.',
        'The store is closed.',
        'This describes the store’s state, not the event of closing it.',
      ],
      ['nakabukas-pinto', 'Nakabukas ang pinto.', 'The door is open.'],
      [
        'nakaupo-tabi',
        'Nakaupo siya sa tabi ko.',
        'He/She is seated beside me.',
      ],
    ],
    words: [
      [
        'babasahin',
        'babasahin',
        'reading material / what will be read',
        'The surrounding article and sentence determine its noun-like use.',
      ],
      ['gawain', 'gawain', 'task / activity'],
      ['inumin', 'inumin', 'beverage / something to drink'],
      ['nakahiga', 'nakahiga', 'lying down'],
      ['nakasara', 'nakasara', 'in a closed state'],
      [
        'nakabukas',
        'nakabukas',
        'in an open state',
        'The root is final-stress bukás “open,” unlike initial-stress búkas “tomorrow.”',
      ],
      ['nakaupo', 'nakaupo', 'seated'],
      ['pinto', 'pinto', 'door'],
    ],
    dialogue: [
      'Checking whether a store has opened',
      'Nakasara ba ang tindahan?',
      'Is the store closed?',
      'Oo, nakasara pa.',
      'Yes, it is still closed.',
      'Nakabukas ang pinto.',
      'Marami akong gawain ngayon.',
      'Nakasara describes the current condition; pa means that the condition continues.',
    ],
  },
  {
    id: 'reciprocal-reduplicated-actions',
    title: 'Group & reciprocal actions',
    titleFil: 'Magkita-kita tayo.',
    description:
      'Talk about people gathering, discussing, helping, writing, or looking at one another.',
    canDo:
      'I can describe a collective action without treating every plural subject alike.',
    soundTitle: 'Give each repeated root its own beat',
    soundModel: 'Magkita-kita. Mag-usap-usap.',
    soundFocus:
      'Repeat the whole root clearly. Keep both kita and both usap portions audible instead of collapsing the middle boundary.',
    syllables: 'mag-ki-TA-ki-TA · mag-ʔU-sap-ʔU-sap',
    pattern: {
      frame:
        'mag- + root-root for a group action · mag- + root + -an for reciprocal action',
      transform: 'Magkita tayo. → Magkita-kita tayo.',
      note: 'Whole-root repetition can present a familiar action as collective or distributed. Reciprocal -an forms such as magtulungan and magsulatan express “one another” more directly; reduplication is not a universal reciprocal rule.',
    },
    phrases: [
      [
        'magkita-kita-bukas',
        'Magkita-kita tayo bukas.',
        'Let’s all meet tomorrow.',
      ],
      [
        'nagkita-kita-kaibigan',
        'Nagkita-kita ang mga kaibigan.',
        'The friends got together.',
        'This is safer than glossing the repeated form mechanically as “met one another.”',
      ],
      [
        'mag-usap-usap-muna',
        'Mag-usap-usap muna tayo.',
        'Let’s discuss it first.',
      ],
      [
        'nag-usap-usap-plano',
        'Nag-usap-usap sila tungkol sa plano.',
        'They discussed the plan among themselves.',
      ],
      [
        'nagtulungan-gawain',
        'Nagtulungan ang mga kaibigan sa gawain.',
        'The friends helped one another with the task.',
      ],
      [
        'nagsulatan-ana-leo',
        'Nagsulatan sina Ana at Leo.',
        'Ana and Leo wrote to one another.',
      ],
      [
        'nagtinginan-bata',
        'Nagtinginan ang mga bata.',
        'The children looked at one another.',
      ],
    ],
    words: [
      ['magkita-kita', 'magkita-kita', 'meet as a group'],
      ['mag-usap-usap', 'mag-usap-usap', 'discuss among yourselves'],
      ['magtulungan', 'magtulungan', 'help one another'],
      ['magsulatan', 'magsulatan', 'write to one another'],
      ['magtinginan', 'magtinginan', 'look at one another'],
      ['isa-t-isa', "isa't isa", 'each other / one another'],
      ['kaibigan', 'kaibigan', 'friend'],
      ['plano', 'plano', 'plan'],
    ],
    dialogue: [
      'After a shared task',
      'Nagtulungan ba sila?',
      'Did they help one another?',
      "Oo, tinulungan nila ang isa't isa.",
      'Yes, they helped one another.',
      'Nag-usap-usap sila tungkol sa plano.',
      'Nakasara ang tindahan.',
      'Nagtulungan already carries reciprocity; isa’t isa makes that relationship explicit in the reply.',
    ],
  },
  {
    id: 'i-focus',
    title: 'Moving and transferring things',
    titleFil: 'Ibigay mo ang libro.',
    description:
      'Use common i- verbs when a thing being given, sent, placed, written, or closed is in focus.',
    canDo:
      'I can give practical instructions and track a transferred or moved item.',
    soundTitle: 'Keep the i- form and repeated syllables audible',
    soundModel: 'Ibigay. Ibinigay. Ibibigay.',
    soundFocus:
      'Practice the three forms as a family. Do not drop the opening i- or the repeated bi syllable in the contemplated form.',
    syllables: 'i-bi-GAY · i-bi-ni-GAY · i-bi-bi-GAY',
    pattern: {
      frame:
        'i- verb + actor + ang focused theme + sa/kay destination · base/command: i- + root · completed: i- with the root’s -in-/-ni- pattern · contemplated: i- + repeated first root syllable + root',
      transform: 'ibigay → ibibigay',
      note: 'Many i- verbs focus a theme that is transferred, moved, or caused to change location or state. Compare ibigay → ibinigay → ibibigay, ilagay → inilagay → ilalagay, and isulat → isinulat → isusulat. Learn each root with its participants; i- does not have one fixed English translation.',
    },
    phrases: [
      ['ibigay-libro', 'Ibigay mo kay Ana ang libro.', 'Give the book to Ana.'],
      [
        'ibinigay-libro',
        'Ibinigay ko kay Ana ang libro.',
        'I gave the book to Ana.',
      ],
      [
        'ibibigay-bukas',
        'Ibibigay ko bukas ang libro.',
        'I will give the book tomorrow.',
      ],
      [
        'ipadala-mensahe',
        'Ipadala mo sa akin ang mensahe.',
        'Send the message to me.',
      ],
      [
        'ilagay-susi',
        'Ilagay mo sa mesa ang susi.',
        'Put the key on the table.',
      ],
      ['isulat-pangalan', 'Isulat mo ang pangalan mo.', 'Write your name.'],
      ['isara-pinto', 'Isara mo ang pinto.', 'Close the door.'],
    ],
    words: [
      ['bigay', 'bigay', 'give (root)'],
      ['padala', 'padala', 'send (root)'],
      ['lagay', 'lagay', 'put / place (root)'],
      ['sulat', 'sulat', 'write (root)'],
      ['sara', 'sara', 'close (root)'],
      ['libro', 'libro', 'book'],
      ['mensahe', 'mensahe', 'message'],
      ['pinto', 'pinto', 'door'],
    ],
    dialogue: [
      'Sending a message',
      'Ano ang ipapadala ko kay Ana?',
      'What should I send to Ana?',
      'Ipadala mo sa kaniya ang mensahe.',
      'Send the message to her.',
      'Ilagay mo sa mesa ang susi.',
      'Nagbasa si Ana ng libro.',
      'The message stays in focus, while kay/sa kaniya marks the destination.',
    ],
  },
];

export const additionalUnits: Unit[] = seeds.map(makeUnit);

const legacyVocabulary: Record<string, WordSeed[]> = {
  greetings: [
    ['kumusta', 'kumusta', 'hello / how are things'],
    ['mabuti', 'mabuti', 'well / good'],
    ['salamat', 'salamat', 'thank you'],
    ['umaga', 'umaga', 'morning'],
    ['hapon', 'hapon', 'afternoon'],
    ['gabi', 'gabi', 'evening'],
    ['ulit', 'ulit', 'again'],
    ['intindi', 'intindi', 'understanding'],
  ],
  introductions: [
    ['pangalan', 'pangalan', 'name'],
    ['taga-saan', 'taga-saan', 'from where'],
    ['nakatira', 'nakatira', 'lives / residing'],
    ['trabaho', 'trabaho', 'work / job'],
    ['ako', 'ako', 'I / me'],
    ['ikaw', 'ikaw', 'you'],
    ['kayo', 'kayo', 'you (respectful/plural)'],
    ['kaibigan', 'kaibigan', 'friend'],
  ],
  needs: [
    ['gusto', 'gusto', 'want / like'],
    ['ayaw', 'ayaw', 'do not want'],
    ['kailangan', 'kailangan', 'need'],
    ['tubig', 'tubig', 'water'],
    ['kape', 'kape', 'coffee'],
    ['tulong', 'tulong', 'help'],
    ['mayroon', 'mayroon', 'there is / has'],
    ['maanghang', 'maanghang', 'spicy'],
  ],
  food: [
    ['pagkain', 'pagkain', 'food'],
    ['tubig', 'tubig', 'water'],
    ['adobo', 'adobo', 'adobo'],
    ['kanin', 'kanin', 'cooked rice'],
    ['masarap', 'masarap', 'delicious'],
    ['order', 'order', 'order'],
    ['bayad', 'bayad', 'payment'],
    ['balot', 'balot', 'wrap'],
  ],
  directions: [
    ['saan', 'saan', 'where'],
    ['istasyon', 'istasyon', 'station'],
    ['diretso', 'diretso', 'straight'],
    ['kanan', 'kanan', 'right'],
    ['kaliwa', 'kaliwa', 'left'],
    ['kanto', 'kanto', 'corner'],
    ['malapit', 'malapit', 'near'],
    ['malayo', 'malayo', 'far'],
  ],
  routine: [
    ['gising', 'gising', 'wake / awake'],
    ['trabaho', 'trabaho', 'work'],
    ['aral', 'aral', 'study'],
    ['uwi', 'uwi', 'go home'],
    ['almusal', 'almusal', 'breakfast'],
    ['tanghali', 'tanghali', 'noon'],
    ['mamaya', 'mamaya', 'later'],
    ['araw-araw', 'araw-araw', 'every day'],
  ],
  plans: [
    ['tayo', 'tayo', 'we, including you'],
    ['kami', 'kami', 'we, not you'],
    ['bukas', 'bukas', 'tomorrow'],
    ['mamaya', 'mamaya', 'later'],
    ['kita', 'kita', 'see / meet'],
    ['sama', 'sama', 'join / accompany'],
    ['puwede', 'puwede', 'can / possible'],
    ['plano', 'plano', 'plan'],
  ],
  help: [
    ['tulong', 'tulong', 'help'],
    ['doktor', 'doktor', 'doctor'],
    ['ospital', 'ospital', 'hospital'],
    ['pulis', 'pulis', 'police'],
    ['masakit', 'masakit', 'painful / hurts'],
    ['ulo', 'ulo', 'head'],
    ['naliligaw', 'naliligaw', 'lost / losing one’s way'],
    ['emergency', 'emergency', 'emergency'],
  ],
};

export const courseVocabulary: Record<string, VocabularyItem[]> =
  Object.fromEntries(
    [
      ...Object.entries(legacyVocabulary),
      ...seeds.map((seed) => [seed.id, seed.words] as const),
    ].map(([unitId, words]) => [
      unitId,
      words.map(([id, fil, en, note]) => ({
        id,
        fil,
        en,
        note:
          note ??
          'Tap the word to hear it, then use it inside a complete phrase.',
      })),
    ]),
  );

export const additionalFoundations: Record<string, FoundationUnit> =
  Object.fromEntries(seeds.map((seed) => [seed.id, makeFoundation(seed)]));
